version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rivy
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rivy
      PORT: 4000
      WEB_ORIGIN: http://localhost:5173
      SEED: "true"
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ./web
    environment:
      VITE_API_BASE: http://localhost:4000
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    volumes:
      - ./web:/app
    depends_on:
      - api

volumes:
  dbdata:
